import { mkdir, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { addComponents, detectPackageManager, initProject, parseArguments, validateRegistryItem } from "../src/index";

const temporaryDirectories: string[] = [];

async function fixture() {
  const cwd = await import("node:fs/promises").then(({ mkdtemp }) => mkdtemp(path.join(os.tmpdir(), "moe-ui-cli-")));
  temporaryDirectories.push(cwd);
  await mkdir(path.join(cwd, "app"), { recursive: true });
  await writeFile(path.join(cwd, "package.json"), JSON.stringify({ dependencies: { next: "16.1.6" } }));
  await writeFile(path.join(cwd, "tsconfig.json"), "{}");
  await writeFile(path.join(cwd, "pnpm-lock.yaml"), "lockfileVersion: '9.0'\n");
  await writeFile(path.join(cwd, "next.config.ts"), 'import type { NextConfig } from "next";\nconst nextConfig: NextConfig = {};\nexport default nextConfig;\n');
  await writeFile(path.join(cwd, "app/layout.tsx"), "export default function Layout({ children }) { return <html><body>{children}</body></html>; }\n");
  await writeFile(path.join(cwd, "app/globals.css"), '@import "tailwindcss";\n');
  return cwd;
}

afterEach(async () => {
  vi.unstubAllGlobals();
  const { rm } = await import("node:fs/promises");
  await Promise.all(temporaryDirectories.splice(0).map((directory) => rm(directory, { recursive: true, force: true })));
});

describe("CLI arguments", () => {
  it("parses init and add options", () => {
    expect(parseArguments(["init", "--yes", "--package-manager", "pnpm", "--no-install"]).options).toMatchObject({ yes: true, packageManager: "pnpm", install: false });
    expect(parseArguments(["add", "button", "dialog", "--overwrite"]).components).toEqual(["button", "dialog"]);
  });

  it("rejects unknown commands and empty add lists", () => {
    expect(() => parseArguments(["nope"])).toThrow("Unknown command");
    expect(() => parseArguments(["add"])).toThrow("Add at least one");
  });
});

describe("project initialization", () => {
  it("detects pnpm and configures an App Router fixture idempotently", async () => {
    const cwd = await fixture();
    expect(await detectPackageManager(cwd)).toBe("pnpm");
    await initProject({ cwd, yes: true, overwrite: false, install: false, packageManager: "pnpm" });
    await writeFile(
      path.join(cwd, "uniwind-types.d.ts"),
      '// NOTE: generated by Uniwind\n/// <reference types="uniwind/types" />\n',
    );
    await initProject({ cwd, yes: true, overwrite: false, install: false, packageManager: "pnpm" });
    expect(await readFile(path.join(cwd, "next.config.ts"), "utf8")).toContain("withMoeUI(nextConfig)");
    expect(await readFile(path.join(cwd, "app/layout.tsx"), "utf8")).toContain("suppressHydrationWarning");
    expect(await readFile(path.join(cwd, "moe-ui.react-native-web.d.ts"), "utf8")).toContain(
      'declare module "react-native-web"',
    );
    expect(JSON.parse(await readFile(path.join(cwd, "components.json"), "utf8"))).toMatchObject({ schemaVersion: 1, typescript: true });
  });

  it("refuses to replace an incompatible existing configuration", async () => {
    const cwd = await fixture();
    await writeFile(path.join(cwd, "components.json"), JSON.stringify({ schemaVersion: 99 }));
    await expect(initProject({ cwd, yes: true, overwrite: false, install: false })).rejects.toThrow(
      "cannot be transformed safely",
    );
    expect(await readFile(path.join(cwd, "next.config.ts"), "utf8")).not.toContain("withMoeUI");
  });
});

describe("registry installation", () => {
  const item = {
    schemaVersion: 1 as const,
    name: "button",
    title: "Button",
    description: "Button",
    category: "foundation",
    type: "registry:ui" as const,
    files: [{ path: "components/ui/button.tsx", target: "components/ui/button.tsx", content: "export const Button = () => null;\n" }],
    dependencies: {},
    registryDependencies: [],
    integrity: "sha256-EBCGwEqsBhLzSUi72HXE5yac0WG/UhGKiMJuLq/PWXU=",
  };

  it("validates schema and installs idempotently", async () => {
    const cwd = await fixture();
    await initProject({ cwd, yes: true, overwrite: false, install: false, packageManager: "pnpm" });
    vi.stubGlobal("fetch", vi.fn(async () => new Response(JSON.stringify(item), { status: 200 })));
    await addComponents(["button"], { cwd, yes: true, overwrite: false, install: false });
    const second = await addComponents(["button"], { cwd, yes: true, overwrite: false, install: false });
    expect(second.files).toEqual([]);
    expect(validateRegistryItem(item).name).toBe("button");
  });

  it("surfaces network and overwrite failures", async () => {
    const cwd = await fixture();
    await initProject({ cwd, yes: true, overwrite: false, install: false, packageManager: "pnpm" });
    vi.stubGlobal("fetch", vi.fn(async () => new Response("missing", { status: 404, statusText: "Not Found" })));
    await expect(addComponents(["missing"], { cwd, yes: true, overwrite: false, install: false })).rejects.toThrow("Unable to fetch");
  });

  it("resolves registry dependencies recursively", async () => {
    const cwd = await fixture();
    await initProject({ cwd, yes: true, overwrite: false, install: false });
    const utilsContent = "export const cn = () => '';\n";
    const component = { ...item, registryDependencies: ["utils"] };
    const utils = {
      ...item,
      name: "utils",
      type: "registry:lib" as const,
      files: [{ path: "lib/utils.ts", target: "lib/utils.ts", content: utilsContent }],
      integrity: `sha256-${await import("node:crypto").then(({ createHash }) => createHash("sha256").update(utilsContent).digest("base64"))}`,
    };
    vi.stubGlobal("fetch", vi.fn(async (request: string | URL | Request) => {
      const name = String(request).endsWith("utils.json") ? utils : component;
      return new Response(JSON.stringify(name), { status: 200 });
    }));
    const result = await addComponents(["button"], { cwd, yes: true, overwrite: false, install: false });
    expect(result.items).toEqual(["button", "utils"]);
    expect(await readFile(path.join(cwd, "lib/utils.ts"), "utf8")).toBe(utilsContent);
  });

  it("protects local changes unless overwrite is explicit", async () => {
    const cwd = await fixture();
    await initProject({ cwd, yes: true, overwrite: false, install: false });
    vi.stubGlobal("fetch", vi.fn(async () => new Response(JSON.stringify(item), { status: 200 })));
    await addComponents(["button"], { cwd, yes: true, overwrite: false, install: false });
    const target = path.join(cwd, "components/ui/button.tsx");
    await writeFile(target, "// local change\n");
    await expect(addComponents(["button"], { cwd, yes: true, overwrite: false, install: false })).rejects.toThrow(
      "--overwrite",
    );
    await addComponents(["button"], { cwd, yes: true, overwrite: true, install: false });
    expect(await readFile(target, "utf8")).toBe(item.files[0].content);
  });
});
